globalThis.runGeoTests=function(){const G=GeoMath,results=[];let passed=0,failed=0;
function test(name,fn){try{fn();passed++;results.push('PASS '+name);}catch(e){failed++;results.push('FAIL '+name+': '+e.message);}}
function assert(x,m='assertion failed'){if(!x)throw Error(m);}function near(a,b,tol=1e-7){assert(Math.abs(a-b)<tol,`${a} != ${b}`);}
function rng(seed){return ()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
test('Unbiased covariance known sample',()=>{const c=G.covariance([[1,2],[2,4],[3,6]],0);near(c[0][0],1);near(c[0][1],2);near(c[1][1],4);});
test('Jacobi reconstructs symmetric matrix',()=>{const a=[[4,1,2],[1,3,.5],[2,.5,5]],e=G.eigen(a),r=G.mul(e.vectors.map(row=>row.map((v,j)=>v*e.values[j])),G.transpose(e.vectors));a.forEach((row,i)=>row.forEach((v,j)=>near(v,r[i][j])));});
test('Distance identity / known diagonal answer',()=>{near(G.distance([[2,0],[0,3]],[[2,0],[0,3]]),0);near(G.distance(G.identity(2),[[Math.E,0],[0,Math.E**2]]),Math.sqrt(5));});
test('Affine invariance and symmetry',()=>{const a=[[2,.3],[.3,1]],b=[[3,-.4],[-.4,2]],p=[[2,1],[.2,1]],cong=x=>G.mul(G.mul(p,x),G.transpose(p));near(G.distance(a,b),G.distance(b,a));near(G.distance(a,b),G.distance(cong(a),cong(b)));});
test('Reject invalid SPD state',()=>{let caught=false;try{G.distance([[-1,0],[0,1]],G.identity(2));}catch{caught=true;}assert(caught);});
test('Derived pressures and regularization',()=>{const e=new G.Engine(rng(1));for(let i=0;i<90;i++){e.step();near(e.vitals[6],(e.vitals[4]+2*e.vitals[5])/3);near(e.vitals[7],e.vitals[4]-e.vitals[5]);assert(G.eigen(e.matrix).values.every(v=>v>=G.EPS-1e-7));near(e.d,G.distance(e.ref,e.matrix));}});
test('Repeated scenarios: calm start, real relationship shift, warning by 90s',()=>{for(let seed=1;seed<=20;seed++){const e=new G.Engine(rng(seed));let first=null;for(let i=0;i<90;i++){e.step();if(e.warning&&first===null)first=e.t;if(e.t<=15)assert(!e.warning,`early warning seed ${seed}`);}assert(first!==null,`no warning seed ${seed}`);assert(e.changes().some(c=>Math.abs(c.value)>1));results.push(`  seed ${seed}: warning ${first}s, final dR ${e.d.toFixed(3)}`);}});
test('Scenario dynamics are distinct',()=>{const healthy=new G.Engine(rng(101),'healthy'),gradual=new G.Engine(rng(101),'gradual'),rapid=new G.Engine(rng(101),'rapid'),noisy=new G.Engine(rng(101),'noisy');for(let i=0;i<45;i++){healthy.step();gradual.step();rapid.step();noisy.step();}assert(!healthy.warning,'healthy warning');assert(!noisy.warning,'noisy stable warning');assert(rapid.d>gradual.d,`rapid ${rapid.d} <= gradual ${gradual.d}`);for(let i=45;i<100;i++)gradual.step();assert(gradual.warning,'gradual warning missing');assert(noisy.raw.slice(-30).some((r,i,a)=>i&&Math.abs(r.v[0]-a[i-1].v[0])>.5),'noisy values not visibly changing');});
test('New runs randomize subject and covariance while preserving derived values',()=>{const starts=[],ids=[],cov=[];for(let seed=1;seed<=5;seed++){const e=new G.Engine(rng(seed),'gradual').start();starts.push(e.vitals.slice(0,6).map(x=>Math.round(x*10)/10).join(','));ids.push(e.id);cov.push(fold(e.ref));near(e.vitals[6],(e.vitals[4]+2*e.vitals[5])/3);near(e.vitals[7],e.vitals[4]-e.vitals[5]);}assert(new Set(starts).size===5,'starting vitals repeated');assert(new Set(ids).size===5,'simulation IDs repeated');assert(new Set(cov.map(x=>x.toFixed(4))).size>1,'covariance not randomized');function fold(m){return m.flat().reduce((s,x,i)=>s+x*(i+1),0);}});
test('Histories bounded / reset returns clean state',()=>{const e=new G.Engine(rng(33));for(let i=0;i<400;i++)e.step();assert(e.history.length<=180&&e.states.length<=180&&e.raw.length<=180&&e.events.length<=60&&e.window.length===36);const n=new G.Engine(rng(2));assert(n.t===0&&n.history.length===0&&!n.warning&&n.id===null);});
return {passed,failed,results};};
